name: Ultimate-Randomizer
version: '1.5.1'
main: io.github.tigerx6.randomizer.Randomizer
api-version: '1.13'
author: TigerX6
commands:
  randomizer:
    description: "General command for the Randomizer"
permissions:
  randomizer.*:
    default: op
    description: Gives access to all Randomizer commands
    children:
      randomizer.start: true
      randomizer.stop: true
      randomizer.shuffle: true
      randomizer.players: true
      randomizer.players.add: true
      randomizer.players.remove: true

  randomizer.randomizer:
    default: true